name: random_cat_facts
description: "Daily Cat Dose."
publish_to: 'none' 

version: 1.1.0+2

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # ðŸŒŸ UI & Design
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  soft_edge_blur: ^0.1.3
  auto_size_text: ^3.0.0
  flutter_animate: ^4.5.2
  flutter_staggered_grid_view: ^0.6.2

  # ðŸ§  State Management & Routing
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  go_router: ^14.8.0

  # ðŸ—‚ï¸ Data, Storage & Utilities
  http: ^1.2.2
  sqflite: ^2.4.1
  path: ^1.9.1
  path_provider: ^2.1.4
  share_plus: ^10.1.4

  # ðŸ› ï¸ App Utilities
  flutter_launcher_icons: ^0.14.2
  flutter_native_splash: ^2.4.0
  rename_app: ^1.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-VariableFont_wght.ttf
          weight: 500
          style: normal

flutter_launcher_icons:
  android: "adaptive"
  ios: true
  image_path: "assets/images/smaller_cat.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/smaller_cat.png"

  web:
    generate: true
    image_path: "assets/images/smaller_cat.png"
    background_color: "#F5A623"
    theme_color: "#F5A623"
  windows:
    generate: true
    image_path: "assets/images/smaller_cat.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/smaller_cat.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/smaller_cat.png
  android: true
  ios: true
  fullscreen: true
  color_ios: "#FFFFFF"
  color_dark: "#FFFFFF"
  image_dark: assets/images/smaller_cat.png
  android_12:
    image: assets/images/smaller_cat.png
    color: "#FFFFFF"
    icon_background_color: "#FFFFFF"
    image_dark: assets/images/smaller_cat.png
    color_dark: "#FFFFFF"
    icon_background_color_dark: "#FFFFFF"
  android_gravity: center
  ios_content_mode: center
